apiVersion: apps/v1
kind: Deployment
metadata:
  name: ad
  labels:
    app: ad-deployment
spec:
  selector:
    matchLabels:
      app: ad-app
  replicas: 1
  template:
    metadata:
      labels:
        app: ad-app
    spec:
      containers:
        - name: cognitive-services-ad-detect
          image: mcr.microsoft.com/azure-cognitive-services/anomaly-detector:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
            limits:
              cpu: 300m
              memory: 2Gi
          env:
            - name: EULA
              value: accept
            - name: billing
              value:  # Localize
            - name: apikey
              value:  # Localize

---
apiVersion: v1
kind: Service
metadata:
  name: lb-ad
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: ad-app

