apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa
  labels:
    app: sa-deployment
spec:
  selector:
    matchLabels:
      app: sa-app
  replicas: 1
  template:
    metadata:
      labels:
        app: sa-app
    spec:
      containers:
        - name: cognitive-services-sa-detect
          image: mcr.microsoft.com/azure-cognitive-services/sentiment
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
            limits:
              cpu: 300m
              memory: 2Gi
          env:
            - name: EULA
              value: accept
            - name: billing
              value:  # Localize
            - name: apikey
              value: # Localize

---
apiVersion: v1
kind: Service
metadata:
  name: wad-sa
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: sa-app

