apiVersion: apps/v1
kind: Deployment
metadata:
  name: ke
  labels:
    app: ke-deployment
spec:
  selector:
    matchLabels:
      app: ke-app
  replicas: 1
  template:
    metadata:
      labels:
        app: ke-app
    spec:
      containers:
        - name: keyphrase
          image: mcr.microsoft.com/azure-cognitive-services/keyphrase
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
            limits:
              cpu: 300m
              memory: 2Gi
          env:
            - name: EULA
              value: accept
            - name: billing
              value: # Localize
            - name: apikey
              value: # Localize

---
apiVersion: v1
kind: Service
metadata:
  name: lb-ke
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: ke-app

